packages:
  # Include all of the core configuration
  core: !include aquapi_mqtt_config.yaml
  
esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: therealfalsereality.aquapi_mqtt
    version: dev # This will be replaced by the github workflows with the `release` version
