substitutions:
  # App Version
  app_version: "25.6.1"

packages:  
  ota_https: !include common/ota_https.yaml
  TheRealFalseReality.device_base: github://TheRealFalseReality/aquapi/common/device_base.yaml@main
  TheRealFalseReality.aquapi_mqtt_base: github://TheRealFalseReality/MyESPHome/aquapi_mqtt_base.yaml@main
  TheRealFalseReality.ph: github://TheRealFalseReality/aquapi/common/ezo_ph.yaml
  TheRealFalseReality.ec: github://TheRealFalseReality/aquapi/common/ezo_ec.yaml
  TheRealFalseReality.dallas: github://TheRealFalseReality/aquapi/common/temperature_dallas.yaml
  TheRealFalseReality.water_level: github://TheRealFalseReality/aquapi/common/water_level.yaml
  TheRealFalseReality.binary: github://TheRealFalseReality/aquapi/common/binary.yaml
  TheRealFalseReality.ezo_orp: github://TheRealFalseReality/aquapi/common/ezo_orp.yaml
  TheRealFalseReality.ezo_co2: github://TheRealFalseReality/aquapi/common/ezo_co2.yaml
  TheRealFalseReality.ezo_do: github://TheRealFalseReality/aquapi/common/ezo_do.yaml
  TheRealFalseReality.ezo_pmp: github://TheRealFalseReality/aquapi/common/ezo_pmp.yaml
  TheRealFalseReality.ezo_pmp_duo: github://TheRealFalseReality/aquapi/common/ezo_pmp_duo.yaml
  # TheRealFalseReality.debug: github://TheRealFalseReality/aquapi/common/debug.yaml