substitutions:
  # names
  name: "aquapi_mqtt"
  friendly_name: "AquaPi MQTT"
  comment: "AquaPi MQTT ESP32 - Aquarium Controller & Monitor"
  project_name: "therealfalsereality.aquapi_mqtt"
  sorting_group_name: "AquaPi "
  import: "false"

dashboard_import:
  package_import_url: github://TheRealFalseReality/aquapi/aquapi_mqtt_config.yaml@main
  import_full_config: "${import}"
      
text_sensor: 
  # AquaPi Version
  - platform: template
    name: "AquaPi Version"
    id: aquapi_version
    icon: mdi:update
    update_interval: '24h'
    lambda: |-
      return {"${app_version}"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    update_interval: '24h'
    lambda: |-
      return {"github.com/TheRealFalseReality/aquapi_mqtt"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic
