substitutions:
  # names
  name: "aquapi_mqtt"
  friendly_name: "AquaPi MQTT"
  comment: "AquaPi MQTT ESP32 - Aquarium Controller & Monitor"
  project_name: "therealfalsereality.aquapi_mqtt"
  sorting_group_name: "AquaPi "
  import: "false"

dashboard_import:
  package_import_url: github://TheRealFalseReality/aquapi/aquapi_mqtt_config.yaml@main
  import_full_config: "${import}"

esp32:
  framework:
    type: esp-idf

api: 
  reboot_timeout: 0s
    
mqtt:
  broker: thefalsehome.duckdns.org
  # broker: homeassistant.local
  port: 8883
  username: mosquitto
  password: !secret mqtt_password
  discovery_prefix: ${name}/homeassistant
  log_topic: ${name}/logs
  skip_cert_cn_check: true
  idf_send_async: false
  certificate_authority: !secret certfile
      
text_sensor: 
  # AquaPi Version
  - platform: template
    name: "AquaPi Version"
    id: aquapi_version
    icon: mdi:update
    update_interval: '24h'
    lambda: |-
      return {"${app_version}"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # GitHub Project URL
  - platform: template
    name: GitHub
    id: github
    icon: mdi:github
    update_interval: '24h'
    lambda: |-
      return {"github.com/TheRealFalseReality/aquapi_mqtt"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic

# Remove Incompatable Components
light:
  - id: !remove internal_led
sensor:
  - id: !remove i2c_devices
button:
  - id: !remove read_ph
  # Read pH Probe
  - platform: template
    name: pH - Read
    id: read_ph
    icon: mdi:read
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(ph_ezo).send_custom("R");
    web_server:
      sorting_group_id: sorting_group_ph
  - id: !remove read_ec
  # Read EC Probe
  - platform: template
    name: EC - Read
    id: read_ec
    icon: mdi:read
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(ec_ezo).send_custom("R");
    web_server:
      sorting_group_id: sorting_group_ec
  - id: !remove read_orp
  # Read ORP Probe
  - platform: template
    name: ORP - Read
    id: read_orp
    icon: mdi:read
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(orp_ezo).send_custom("R");
    web_server:
      sorting_group_id: sorting_group_orp
  - id: !remove read_co2
  # Read CO2 Probe
  - platform: template
    name: CO2 - Read
    id: read_co2
    icon: mdi:read
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(co2_ezo).send_custom("R");
    web_server:
      sorting_group_id: sorting_group_co2
  - id: !remove read_do
  # Read DO Probe
  - platform: template
    name: DO - Read
    id: read_do
    icon: mdi:read
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(do_ezo).send_custom("R");
    web_server:
      sorting_group_id: sorting_group_do
