substitutions:
  # names
  name: "aquapi-mqtt"
  friendly_name: "AquaPi MQTT"
  comment: "AquaPi MQTT ESP32 - Aquarium Controller & Monitor"
  project_name: "therealfalsereality.aquapi_mqtt"
  sorting_group_name: "AquaPi"
  import: "false"
  mqtt_broker: "localhost"
  mqtt_password: ""
  mqtt_port: "1883"
  mqtt_user: "mosquitto"
  mqtt_certifile: ""

dashboard_import:
  package_import_url: github://TheRealFalseReality/aquapi_mqtt/aquapi_mqtt_config.yaml@main
  import_full_config: "${import}"

esp32:
  framework:
    type: esp-idf

api: 
  reboot_timeout: 0s
      
text_sensor: 
  # AquaPi MQTT Version
  - platform: template
    name: "AquaPi MQTT Version"
    id: aquapi_version_mqtt
    icon: mdi:update
    lambda: |-
      return {"${app_version_mqtt}"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # GitHub Project URL
  - platform: template
    name: GitHub MQTT
    id: github_mqtt
    icon: mdi:github
    lambda: |-
      return {"github.com/TheRealFalseReality/aquapi_mqtt"};
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: sorting_group_diagnostic

# Remove Incompatable Components
light:
  - id: !remove internal_led
  
# AquaPi MQTT
mqtt:
  broker: ${mqtt_broker}
  port: ${mqtt_port}
  username: ${mqtt_user}
  password: ${mqtt_password}
  # discovery_prefix: ${mqtt_prefix}/homeassistant
  # log_topic: ${name}/logs
  skip_cert_cn_check: true
  idf_send_async: false
  certificate_authority: ${mqtt_certifile}
