substitutions:
  ota_update_interval: 24h

ota:
  - platform: http_request

http_request:
  verify_ssl: false

update:
  - platform: http_request
    name: AquaPi MQTT Firmware Update
    id: update_firmware_sensor
    entity_category: 'diagnostic'
    update_interval: ${ota_update_interval}
    icon: mdi:update
    source: https://therealfalsereality.github.io/aquapi_mqtt/firmware/aquapi_mqtt.manifest.json
    on_update_available:
      then:
        - button.press: update_firmware
    web_server:
      sorting_group_id: sorting_group_diagnostic

button:
  - platform: template
    id: update_firmware
    name: Update AquaPi MQTT Firmware - Stable
    entity_category: "config"
    icon: mdi:update
    # disabled_by_default: true
    web_server:
      sorting_group_id: sorting_group_config
    on_press: 
        - if:
            condition: 
              - update.is_available: update_firmware_sensor
            then:
              - ota.http_request.flash:
                  md5_url: https://therealfalsereality.github.io/aquapi_mqtt/firmware/aquapi_mqtt-esp32.ota.bin.md5
                  url: https://therealfalsereality.github.io/aquapi_mqtt/firmware/aquapi_mqtt-esp32.ota.bin
